# app/dtos/__init__.py
from .property_dto import (
    AddressRequest,
    AddressResponse,
    CreateHouseRequest,
    CreateApartmentRequest,
    UpdatePropertyRequest,
    PropertyResponse,
    PropertyListResponse,
    PortfolioStatsResponse,
)
from .favorite_dto import (
    FavoriteResponse,
    PropertyDetailsDTO,
    FavoriteListResponse,
    FavoriteStatusResponse,
    FavoritesCountResponse,
)
from .image_dto import (
    ImageUploadRequest,
    ImageResponse,
    ImageDataResponse,
    ImagesListResponse,
    ReorderImagesRequest,
)
from .proposal_dto import (
    CreateProposalRequest,
    RespondProposalRequest,
    ProposalResponse,
    ProposalListResponse,
    UserInfoDTO,
    PropertyInfoDTO,
    ProposalWithUserResponse,
    ProposalWithUserListResponse,
)
from .visit_dto import (
    CreateVisitRequest,
    UpdateVisitRequest,
    CompleteVisitRequest,
    CancelVisitRequest,
    VisitResponse,
    VisitListResponse,
    VisitWithUserResponse,
    VisitWithUserListResponse,
)

__all__ = [
    "AddressRequest",
    "AddressResponse",
    "CreateHouseRequest",
    "CreateApartmentRequest",
    "UpdatePropertyRequest",
    "PropertyResponse",
    "PropertyListResponse",
    "PortfolioStatsResponse",
    "FavoriteResponse",
    "PropertyDetailsDTO",
    "FavoriteListResponse",
    "FavoriteStatusResponse",
    "FavoritesCountResponse",
    "ImageUploadRequest",
    "ImageResponse",
    "ImageDataResponse",
    "ImagesListResponse",
    "ReorderImagesRequest",
    "CreateProposalRequest",
    "RespondProposalRequest",
    "ProposalResponse",
    "ProposalListResponse",
    "UserInfoDTO",
    "PropertyInfoDTO",
    "ProposalWithUserResponse",
    "ProposalWithUserListResponse",
    "CreateVisitRequest",
    "UpdateVisitRequest",
    "CompleteVisitRequest",
    "CancelVisitRequest",
    "VisitResponse",
    "VisitListResponse",
    "VisitWithUserResponse",
    "VisitWithUserListResponse",
]
